title: Blog Bibliotheks- und Archivinformatik
author: stemorit
description: > # this means to ignore newlines until "baseurl:"
  Vorlage f√ºr ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2020


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
